### ISSUE TITLE
Reduce Docker image size

### ISSUE THREAD

**Issue by ughe** [OffchainLabs/arb-validator#15]
Images sizes were as low as 30MB (see #11). PR #14 balloons all validator image sizes to 80MB.

One way to keep both build caching and a slim static build is to split the process into 2 separate Dockerfiles (since internal Dockerfile stages cannot be exported easily). The first would either produce 80MB including the build executables and the build cache. The second would just use the executables.

**Comment by hkalodner** [comment]
It turns out that the running validator docker image doesn't actually store the build cache part in memory so this is a non-issue
